Sparta/src/Entity/Model.php
<?php

namespace App\Entity;

use App\Repository\ModelRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ModelRepository::class)
 */
class Model
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $text;

    /**
     * @ORM\OneToMany(targetEntity=ModelInfo::class, mappedBy="modelID",cascade={"persist"})
     */
    private $modelInfoID;

    /**
     * @ORM\OneToMany(targetEntity=Slider::class, mappedBy="modelID",cascade={"persist"})
     */
    private $sliderID;

    /**
     * @ORM\Column(type="json")
     */
    private $category = [];

    public function __construct()
    {
        $this->modelInfoID = new ArrayCollection();
        $this->sliderID = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(?string $text): self
    {
        $this->text = $text;

        return $this;
    }

    /**
     * @return Collection|ModelInfo[]
     */
    public function getModelInfoID(): Collection
    {
        return $this->modelInfoID;
    }

    public function addModelInfoID(ModelInfo $modelInfoID): self
    {
        if (!$this->modelInfoID->contains($modelInfoID)) {
            $this->modelInfoID[] = $modelInfoID;
            $modelInfoID->setModelID($this);
        }

        return $this;
    }

    public function removeModelInfoID(ModelInfo $modelInfoID): self
    {
        if ($this->modelInfoID->contains($modelInfoID)) {
            $this->modelInfoID->removeElement($modelInfoID);
            // set the owning side to null (unless already changed)
            if ($modelInfoID->getModelID() === $this) {
                $modelInfoID->setModelID(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Slider[]
     */
    public function getSliderID(): Collection
    {
        return $this->sliderID;
    }

    public function addSliderID(Slider $sliderID): self
    {
        if (!$this->sliderID->contains($sliderID)) {
            $this->sliderID[] = $sliderID;
            $sliderID->setModelID($this);
        }

        return $this;
    }

    public function removeSliderID(Slider $sliderID): self
    {
        if ($this->sliderID->contains($sliderID)) {
            $this->sliderID->removeElement($sliderID);
            // set the owning side to null (unless already changed)
            if ($sliderID->getModelID() === $this) {
                $sliderID->setModelID(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?array
    {
        return $this->category;
    }

    public function setCategory(array $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }
}

Sparta/src/Entity/Slider.php
<?php

namespace App\Entity;

use App\Repository\SliderRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SliderRepository::class)
 */
class Slider
{
    protected $file;


    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Model::class, inversedBy="sliderID")
     * @ORM\JoinColumn(nullable=false)
     */
    private $modelID;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slider_img;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getModelID(): ?Model
    {
        return $this->modelID;
    }

    public function setModelID(?Model $modelID): self
    {
        $this->modelID = $modelID;

        return $this;
    }

    public function getSliderImg(): ?string
    {
        return $this->slider_img;
    }

    public function setSliderImg(string $slider_img): self
    {
        $this->slider_img = $slider_img;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @param mixed $file
     */
    public function setFile($file): void
    {
        $this->file = $file;
    }
}

Sparta/src/Controller/ModelController.php
<?php


namespace App\Controller;


use App\Entity\Model;
use App\Form\ModelFormType;
use App\Repository\ModelInfoRepository;
use App\Repository\ModelRepository;
use App\Repository\SliderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @Route ("/model")
 */
class ModelController extends AbstractController
{
    /**
     * @param ModelRepository $modelRepository
     * @Route ("/", name="model_index")
     * @return Response
     */
//    load all models
    public function index(ModelRepository $modelRepository): Response
    {
        return $this->render('model/modelList.html.twig', ['models' => $modelRepository->findAll()]);
    }

    /**
     * @Route("/modelinfo/{id}", name="model_info", methods={"GET","POST"})
     * @param $id
     * @param ModelRepository $modelRepository
     * @param SliderRepository $sliderRepository
     * @param ModelInfoRepository $modelInfoRepository
     * @return Response
     */
//        load individual model
    public function ModelInfo($id, ModelRepository $modelRepository, SliderRepository $sliderRepository, ModelInfoRepository $modelInfoRepository): Response
    {
        return $this->render('model/modelInfo.html.twig', [
            'model' => $modelRepository->findOneBy(['id' => $id]),
            'modelsInfo' => $modelInfoRepository->findInfo($id),
            'sliders' => $sliderRepository->findBy(['modelID' => $id])]);
    }


    /**
     * @Route("/new", name="model_new", methods={"GET","POST"})
     * @param SluggerInterface $slugger
     * @param Request $request
     * @return RedirectResponse|Response
     */

    public function newModel(SluggerInterface $slugger, Request $request)
    {

        $model = new Model();

        $form = $this->createForm(ModelFormType::class, $model);
        $form->handleRequest($request);

//          check if form is submit
        if ($form->isSubmitted() && $form->isValid()) {
//         logic to handle img of model
            /** @var UploadedFile $imgfile
             */
            $imgfile = $form->get('img')->getData();
            if ($imgfile) {
                $originalImgFilename = pathinfo($imgfile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeImgFilename = $slugger->slug($originalImgFilename);
                $newImgFilename = $safeImgFilename . '-' . uniqid('', true) . '.' . $imgfile->guessExtension();

                try {
                    $newImgFilename = $imgfile->move($this->getParameter('model_img_directory'), $newImgFilename);
                } catch (FileException $e) {
                }
                $model->setImg($newImgFilename);
            }

//         logic to handle img of slider these one is duplicate because otherwise the handling of the slider was too complicated
            $sliderfiles = $form->get('sliderID')->getData();
            foreach ($sliderfiles as $file) {
                /** @var UploadedFile $sliderfile */
                $sliderfile = $file->getFile();
                $originalSliderFilename = pathinfo($sliderfile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeSliderFilename = $slugger->slug($originalSliderFilename);
                $newSliderFilename = $safeSliderFilename . '-' . uniqid('', true) . '.' . $sliderfile->guessExtension();
                try {
                    $newSliderFilename = $sliderfile->move($this->getParameter('model_img_directory'), $newSliderFilename);
                } catch (FileException $e) {
                }
                $file->setSliderImg($newSliderFilename);
            }
//            submit form
            $modelManager = $this->getDoctrine()->getManager();
            $modelManager->persist($model);
            $modelManager->flush();
            return $this->redirectToRoute('model_index');

        }
//        render page
        return $this->render('model/new.html.twig', ['form' => $form->createView()]);

    }
}

Sparta/templates/Model/_delete_form.html.twig
<form method="post" action="{{ path('model_index', {'id': model.id}) }}" onsubmit="return confirm('Weet u zeker dat u dit wilt verwijderen');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ model.id) }}">
    <button class="btn-light cst-btn bg-color text-white  pl-3 pr-3 p-2 mt-3 mb-5">Verwijderen</button>
</form>

Sparta/templates/Model/modelInfo.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    SBC|Model
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/js/splide.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var secondarySlider = new Splide('#secondary-slider', {
                rewind: true,
                fixedWidth: 100,
                fixedHeight: 64,
                isNavigation: true,
                gap: 10,
                focus: 'center',
                pagination: false,
                cover: true,
                breakpoints: {
                    '600': {
                        fixedWidth: 66,
                        fixedHeight: 40,
                    }
                }
            }).mount();

            var primarySlider = new Splide('#primary-slider', {
                type: 'fade',
                heightRatio: 0.5,
                pagination: false,
                arrows: false,
                cover: true,
            }); // do not call mount() here.

            primarySlider.sync(secondarySlider).mount();
        });
    </script>
{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/css/splide.min.css">

{% endblock %}
{% block body %}
<div class="mx-auto mt-5 text-justify w-50 p-2 text-white bg-color">
    {% if sliders is not empty %}
        <div id="primary-slider" class="splide">
            <div class="splide__track">
                <ul class="splide__list">
                    {% for slider in sliders %}
                        <li class="splide__slide"><img class="img-fluid" src="{{ asset(slider.sliderImg) }}"/></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div id="secondary-slider" class="splide">
            <div class="splide__track">
                <ul class="splide__list">
                    {% for slider in sliders %}
                        <li class="splide__slide"><img src="{{ asset(slider.sliderImg) }}"/></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% else %}
        <img class="w-100" alt="{{ model.name }}" src="{{ asset(model.img) }}"/>
    {% endif %}
    <hr class="brd">
    <div class="float-right">
        <h6 class="mb-1">Categoriën</h6>
        <ul class="list-group list-group-horizontal">
            {% for category in model.category %}
                <li class="list-group-item text-center text-white bg-color no-brdrd border-white"> {{ category|capitalize }}</li>
            {% endfor %}
        </ul>
    </div>
    <h4>{{ model.name }}</h4>
    <p>{{ model.text }}</p>
    {% if modelsInfo is not empty %}
        <hr class="brd">
        <h5>Technische gegevens</h5>
        <div class="table-responsive">
            <table class="table pl-3 pr-3">
                <thead>
                <tr>
                    <th class="text-white text-center" scope="col">Type</th>
                    <th class="text-white text-center" scope="col">Info</th>
                </tr>
                </thead>
                <tbody>
                {% for modelInfo in modelsInfo %}
                    <tr>
                        <td scope="row" class="text-center text-white"> {{ modelInfo.type|capitalize }}</td>
                        <td class="text-center text-white">{{ modelInfo.info }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
</div>
<div class="mx-auto mt-1 text-justify w-50 mb-5">
    <a class="under text-body" href="{{ path('model_index')}}">&lt;terug naar overzicht</a>
</div>
{% endblock %}

Sparta/templates/Model/modelList.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    SBC|Modellen
{% endblock %}
{% block body %}
    <div class="mx-auto mt-3 text-justify w-50 p-2 px-3">
        <h3>Modellen</h3>
        {% if is_granted('ROLE_ADMIN') %}
        <div class="float-right">
            <a class="btn bg-color text-white cst-btn" href="{{ path('model_new') }}">Onderwerp toevoegen</a>
        </div>
        {% endif %}
    </div>
    <div class="mx-auto mt-3 text-justify w-50 p-2">
        <div class="card-deck">
            {% for model in models %}
                <div class="col-sm-6">
                    <div class="card clr-crd">
                        <img class="card-img-top clr-crd" src="{{ asset(model.img) }}" alt="{{ model.name }}">
                        <div class="card-body bg-color text-white no-brdrd">
                            <h5 class="card-title">{{ model.name }}</h5>
                            <p class="card-text">
                                {{ model.text }}
                            </p>
                             <a href="{{ path('model_info',{'id': model.id}) }}"
                             class="text-white under float-right">Meer info</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

Sparta/templates/Model/new.html.twig
{% extends 'base.html.twig' %}
{% import _self as formMacros %}
{% block title %}
    SBC| Model toevoegen
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('JQUERY/collectionModel.js') }}"></script>
{% endblock %}
{% block nav %}
{% endblock %}
{% block body %}
    <div class="mx-auto my-auto text-justify w-50 p-2">
        {% form_theme form 'form/error_form.html.twig' %}
        {% form_theme form.category 'bootstrap_4_layout.html.twig' %}
        {{ form_start(form) }}
        {{ form_widget(form.name) }}<br>
        {{ form_widget(form.text) }}
        {{ form_label(form.img) }}
        {{ form_widget(form.img) }}
        {{ form_row(form.category) }}
    <ul class="list-group" id="modelInfo-fields-list"
        data-prototype="{{ formMacros.customModelCollection(form.modelInfoID.vars.prototype)|e }}"
        data-widget-tags="{{ '<li class="list-group-item"></li>'|e }}"
        data-widget-counter="{{ form.modelInfoID|length }}">
    </ul>
    <button type="button"
            class="modelInfo mt-2 mb-4 cst-col-btn"
            data-list-selector="#modelInfo-fields-list">Voeg info toe
    </button>

    <ul class="list-group" id="slider-fields-list"
        data-prototype="{{ formMacros.customSliderCollection(form.sliderID.vars.prototype)|e }}"
        data-widget-tags="{{ '<li class="list-group-item"></li>'|e }}"
        data-widget-counter="{{ form.modelInfoID|length }}">
    </ul>
    <button type="button"
            class="slider mt-2 cst-col-btn"
            data-list-selector="#slider-fields-list">Voeg foto slider toe
    </button>

    {{ form_row(form.submit) }}
    {{ form_end(form) }}
    <div class="text-center">
        <a href="{{ path('model_index') }}" class="text-body under">annuleren</a>
    </div>
    </div>
{% endblock %}
{% block footer %}
{% endblock %}

{% macro customModelCollection(modelInfoID) %}
    <div class="col-xs-4 js-genus-scientist-item">
        {{ form_errors(modelInfoID) }}
        {{ form_label(modelInfoID.type) }}
        <br>
        {{ form_widget(modelInfoID.type) }}
        <br>
        {{ form_label(modelInfoID.info) }}
        <br>
        {{ form_widget(modelInfoID.info) }}
    </div>
{% endmacro %}

{% macro customSliderCollection(sliderID) %}
    <div class="col-xs-4 js-genus-scientist-item">
        {{ form_errors(sliderID) }}
        {{ form_label(sliderID.file) }}
        <br>
        {{ form_widget(sliderID.file) }}
    </div>
{% endmacro %}