Sparta/src/Entity/Document.php
<?php

namespace App\Entity;

use App\Repository\DocumentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DocumentRepository::class)
 */
class Document
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $document;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="integer")
     */
    private $Category;

    /**
     * @ORM\Column(type="boolean")
     */
    private $for_all;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(?string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getDocument(): ?string
    {
        return $this->document;
    }

    public function setDocument(string $document): self
    {
        $this->document = $document;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getCategory():  ?int
    {
        return $this->Category;
    }

    public function setCategory(int $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getForAll(): ?bool
    {
        return $this->for_all;
    }

    public function setForAll(bool $for_all): self
    {
        $this->for_all = $for_all;

        return $this;
    }
}

Sparta/src/Controller/DocumentController.php
<?php


namespace App\Controller;


use App\Entity\Document;
use App\Form\DocumentFormType;
use App\Repository\DocumentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;


/**
 * @Route("/document")
 */
class DocumentController extends AbstractController
{
    /**
     * @Route("/", name="document", methods={"GET","POST"})
     * @param DocumentRepository $documentRepository
     * @return Response
     */
//load all document file
    public function document(DocumentRepository $documentRepository): Response
    {
        return $this->render('document/document.html.twig', ['documents' => $documentRepository->findAll()]);
    }

    /**
     * @Route("-category/{number}", name="document_category", methods={"GET","POST"})
     * @param $number
     * @param DocumentRepository $documentRepository
     * @return Response
     */
//load all files with category
    public function CategoryDocument($number, DocumentRepository $documentRepository): Response
    {
        return $this->render('document/document.html.twig', ['documents' => $documentRepository->findBy(['Category'=>$number])]);
    }

    /**
     * @Route("/new", name="document_new", methods={"GET","POST"})
     * @param SluggerInterface $slugger
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
//  add new document
    public  function newDocument(SluggerInterface $slugger, Request $request){

        $document = new Document();

        $form = $this->createForm(DocumentFormType::class, $document);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
//            upload document
            /** @var UploadedFile $documentfile
             */
            $documentfile = $form->get('document')->getData();
            $originalDocumentFilename = pathinfo($documentfile->getClientOriginalName(), PATHINFO_FILENAME);
            $safeDocumentFilename = $slugger->slug($originalDocumentFilename);
            $newDocumentFilename = $safeDocumentFilename . '-' . uniqid('', true) . '.' . $documentfile->guessExtension();

            try {
                $newDocumentFilename = $documentfile->move($this->getParameter('document_directory'), $newDocumentFilename);
            } catch (FileException $e) {
            }

//          upload foto kaft
            /** @var UploadedFile $imgfile
             */
            $imgfile = $form->get('img')->getData();
            if ($imgfile) {
                $originalImgFilename = pathinfo($imgfile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeImgFilename = $slugger->slug($originalImgFilename);
                $newImgFilename = $safeImgFilename . '-' . uniqid('', true) . '.' . $imgfile->guessExtension();

                try {
                    $newImgFilename = $imgfile->move($this->getParameter('document_img_directory'), $newImgFilename);
                } catch (FileException $e) {
                }
                $document->setImg($newImgFilename);
            }



            $document->setDocument($newDocumentFilename);

            $documentManager = $this->getDoctrine()->getManager();
            $documentManager->persist($document);
            $documentManager->flush();
            return $this->redirectToRoute('document');

        }
        return $this->render('document/new.html.twig', ['form' => $form->createView()]);

    }

    /**
     * @Route("/{id}", name="document_delete", methods={"DELETE"})
     * @param Request $request
     * @param Document $document
     * @return Response
     */
//    delete document
    public function documentDelete(Request $request, Document $document): Response
    {
        if ($this->isCsrfTokenValid('delete' . $document->getId(), $request->request->get('_token'))) {
            $filesystem = new Filesystem();
            if ($document->getImg() !== null){
                $filesystem->remove($document->getImg());
            }
            $filesystem->remove($document->getDocument());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($document);
            $entityManager->flush();
        }
        return $this->redirectToRoute('document');


    }
}

Sparta/templates/Document/_delete_form.html.twig
<form method="post" action="{{ path('document_delete', {'id': document.id}) }}" onsubmit="return confirm('Weet u zeker dat u dit wilt verwijderen');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ document.id) }}">
    <button class="btn-light cst-btn bg-color text-white  pl-3 pr-3 p-2 mt-3 mb-5">Verwijderen</button>
</form>

Sparta/templates/Document/document.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    SBC|Documenten
{% endblock %}
{% block body %}
    <div class="mx-auto mt-3 text-justify w-50 p-2">
        <div class="float-right">
            <div class="dropdown show">
                <a class=" btn btn-light cst-btn bg-color text-white  pl-3 pr-3 p-2 " href="#" role="button"
                   id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Selecteer Categorie
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a class="dropdown-item" href="{{ path('document') }}">Alle documenten</a>
                    <a class="dropdown-item" href="{{ path('document_category',{'number': 1}) }}">Artikelen uit tijdschriften</a>
                    <a class="dropdown-item" href="{{ path('document_category',{'number': 2}) }}">Divers</a>
                    <a class="dropdown-item" href="{{ path('document_category',{'number': 3}) }}">Folder</a>
                    <a class="dropdown-item" href="{{ path('document_category',{'number': 4}) }}">Handleidingen</a>
                    <a class="dropdown-item" href="{{ path('document_category',{'number': 5}) }}">Koeriers</a>
                    <a class="dropdown-item" href="{{ path('document_category',{'number': 6}) }}">Motorisch</a>
                    <a class="dropdown-item" href="{{ path('document_category',{'number': 7}) }}">Prijslijsten</a>
                    <a class="dropdown-item" href="{{ path('document_category',{'number': 8}) }}">Club merchandise</a>
                    <a class="dropdown-item" href="{{ path('document_category',{'number': 9}) }}">Club Documenten</a>
                    <a class="dropdown-item" href="{{ path('document_category',{'number': 10}) }}">Ontwerp
                        tekeningen</a>
                    <a class="dropdown-item" href="{{ path('document_category',{'number': 11}) }}">Bijdragen van
                        leden</a>
                    {% if is_granted('ROLE_ADMIN') %}
                    <div class="dropdown-divider"> </div>
                        <a class="dropdown-item" href="{{ path('document_new') }}">Nieuwe toevoegen</a>

                {% endif %}
                </div>
            </div>
        </div>
        <h3>Documenten</h3>
    </div>
    <div class="mx-auto mt-3 text-justify w-50 p-2">
        {% if documents is not empty %}
            {% for document in documents %}
                {% if document.forAll or  is_granted('ROLE_PAYED') %}
                    <div class="row">
                        <div class="col-12">
                            <div class="card clr-crd text-white ">
                                <div class="card-horizontal ">
                                    {% if document.img is not empty %}
                                        <div class="img-square-wrapper">
                                            <div class="img-con">
                                                <img class="img-fluid mx-auto cnt-img" src="{{ asset(document.img) }}"
                                                     alt="{{ document.title }}">
                                            </div>
                                        </div>
                                    {% endif %}
                                    <div class="card-body card bg-color brd">
                                        <div class="h-100">
                                            <h4 class="card-title">{{ document.title }}</h4>
                                            <p class="card-text">{{ document.description }}</p>
                                            <a href="{{ asset(document.document) }}"
                                               class="text-white under float-right">document Inzien</a>
                                        </div>
                                    </div>
                                </div>
                                {% if is_granted('ROLE_ADMIN') %}
                                    <div>
                                        {{ include('document/_delete_form.html.twig') }}
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% else %}
            <h3 class="text-center">Er zijn geen documenten in deze categorie, sorry</h3>
        {% endif %}
    </div>
{% endblock %}

Sparta/templates/Document/new.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    SBC| Document toevoegen
{% endblock %}
{% block nav %}
{% endblock %}
{% block body %}
    <div class="mx-auto my-auto text-justify w-50 p-2">
        {% form_theme form 'form/error_form.html.twig' %}
        {{ form_start(form) }}
        {{ form_errors(form) }}
        {{ form_widget(form.title) }}
        {{ form_widget(form.description) }}
        {{ form_row(form.category) }}
        {{ form_label(form.document) }}
        {{ form_widget(form.document) }}
        <br>
        {{ form_label(form.img) }}
        {{ form_widget(form.img) }}
        <br><br>
        {{ form_row(form.forAll) }}
        {{ form_row(form.submit) }}
        {{ form_end(form) }}
        <div class="text-center">
            <a href="{{ path('document') }}" class="text-body under">annuleren</a>
        </div>
    </div>
{% endblock %}
{% block footer %}
{% endblock %}